### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by JiewenKuang** [williamljb/DifferentiableCloth#12]
`/home/zitman/anaconda3/envs/phi_sft/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   84 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
/home/zitman/DifferentiableCloth-master/pybind/bind.cpp:4:10: fatal error: collision.hpp: no such file or directory
    4 | #include "collision.hpp"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/zitman/anaconda3/envs/phi_sft/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/zitman/anaconda3/envs/phi_sft/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
`

I searched the source file collision.hpp to find this problem, but an error will be reported when compiling

**Comment by CWEzio** [comment]
Hi, I encounter the same problem. Could you please tell how you solved this problem?

**Comment by CWEzio** [comment]
For anyone who need, I solve this by replacing change the `include_dirs` in `setup.py` to absolute path.
